spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
#    open-in-view: 'false'
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${ID}
    username: root
    url: jdbc:mysql://localhost:3306/confiserie?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN
server:
  port: 8080
cloudinary:
  cloud-name: diuhayhix
  api-key: 973864325855613
  api-secret: "${SECRET}"
